// rotompc-client/src/hooks/useAuthSessionSync.js

import { useCallback, useEffect, useRef } from "react";

import * as userService from "@/services/UserService";

import {
  AUTH_UPDATE_EVENT,
  clearAuthSession,
  getAuthToken,
  updateStoredUser,
} from "@/utils/authSession";

/* =========================================================
   CONFIG
========================================================= */

const SESSION_REFRESH_INTERVAL = 60 * 1000;

/* =========================================================
   EXTRACT PROFILE

   Supports several common backend response shapes:

   { user: {...} }
   { profile: {...} }
   { data: {...} }
   {...}
========================================================= */

const extractProfile = (response) => {
  const payload = response?.data;

  if (!payload) {
    return null;
  }

  return payload.user || payload.profile || payload.data || payload;
};

/* =========================================================
   AUTH SESSION SYNC
========================================================= */

const useAuthSessionSync = () => {
  const refreshingRef = useRef(false);

  const mountedRef = useRef(true);

  const lastTokenRef = useRef(null);

  /* =====================================================
       REFRESH
    ===================================================== */

  const refreshSession = useCallback(async ({ silent = true } = {}) => {
    const token = getAuthToken();

    if (!token) {
      lastTokenRef.current = null;

      return null;
    }

    if (refreshingRef.current) {
      return null;
    }

    refreshingRef.current = true;

    try {
      const response = await userService.fetchMyProfile();

      if (!mountedRef.current) {
        return null;
      }

      const profile = extractProfile(response);

      if (!profile) {
        throw new Error("Profile response was empty.");
      }

      /*
       * Merge MongoDB-backed profile
       * into the local cache.
       */

      const updatedUser = updateStoredUser(profile);

      lastTokenRef.current = token;

      return updatedUser;
    } catch (error) {
      const status = error?.response?.status;

      /*
       * Only destroy the session when
       * the server explicitly says the
       * authentication token is invalid.
       */

      if (status === 401) {
        console.warn("[RotomPC] Session expired.");

        clearAuthSession();

        lastTokenRef.current = null;

        return null;
      }

      if (!silent) {
        console.error("[RotomPC] Unable to refresh trainer session:", error);
      }

      return null;
    } finally {
      refreshingRef.current = false;
    }
  }, []);

  /* =====================================================
       INITIAL LOAD
    ===================================================== */

  useEffect(() => {
    mountedRef.current = true;

    lastTokenRef.current = getAuthToken();

    refreshSession({
      silent: false,
    });

    return () => {
      mountedRef.current = false;
    };
  }, [refreshSession]);

  /* =====================================================
       PERIODIC REFRESH
    ===================================================== */

  useEffect(() => {
    const interval = window.setInterval(
      () => {
        if (document.visibilityState === "visible" && getAuthToken()) {
          refreshSession();
        }
      },

      SESSION_REFRESH_INTERVAL,
    );

    return () => {
      window.clearInterval(interval);
    };
  }, [refreshSession]);

  /* =====================================================
       TAB FOCUS

       Very important for Vercel/mobile.
       Users can leave RotomPC open for a long time.
    ===================================================== */

  useEffect(() => {
    const handleFocus = () => {
      if (getAuthToken()) {
        refreshSession();
      }
    };

    const handleVisibility = () => {
      if (document.visibilityState === "visible" && getAuthToken()) {
        refreshSession();
      }
    };

    window.addEventListener("focus", handleFocus);

    document.addEventListener("visibilitychange", handleVisibility);

    return () => {
      window.removeEventListener("focus", handleFocus);

      document.removeEventListener("visibilitychange", handleVisibility);
    };
  }, [refreshSession]);

  /* =====================================================
       LOGIN / LOGOUT / PROFILE EVENT

       saveAuthSession() dispatches local-auth-update.

       Only force a server refresh when the token itself
       changed so the update event generated by hydration
       cannot create an infinite request loop.
    ===================================================== */

  useEffect(() => {
    const handleAuthUpdate = () => {
      const token = getAuthToken();

      if (!token) {
        lastTokenRef.current = null;

        return;
      }

      if (token !== lastTokenRef.current) {
        lastTokenRef.current = token;

        refreshSession({
          silent: false,
        });
      }
    };

    window.addEventListener(AUTH_UPDATE_EVENT, handleAuthUpdate);

    return () => {
      window.removeEventListener(AUTH_UPDATE_EVENT, handleAuthUpdate);
    };
  }, [refreshSession]);

  /* =====================================================
       MULTIPLE TABS
    ===================================================== */

  useEffect(() => {
    const handleStorage = (event) => {
      if (event.key !== "token" && event.key !== "user") {
        return;
      }

      const token = getAuthToken();

      if (!token) {
        lastTokenRef.current = null;

        return;
      }

      lastTokenRef.current = token;

      refreshSession();
    };

    window.addEventListener("storage", handleStorage);

    return () => {
      window.removeEventListener("storage", handleStorage);
    };
  }, [refreshSession]);

  return {
    refreshSession,
  };
};

export default useAuthSessionSync;
