// rotompc-server/models/Articles.js

const mongoose = require("mongoose");

const articleSchema = new mongoose.Schema(
  {
    /* =====================================================
       ARTICLE IDENTITY
    ===================================================== */

    id: {
      type: String,
      required: true,
      unique: true,
      index: true,
      trim: true,
    },

    /*
     * Generated by createUniqueSlug()
     * inside articleController.
     */
    name: {
      type: String,
      required: true,
      unique: true,
      index: true,
      lowercase: true,
      trim: true,
    },

    /* =====================================================
       CONTENT
    ===================================================== */

    title: {
      type: String,
      required: true,
      trim: true,
      maxlength: 150,
    },

    desc: {
      type: String,
      default: "",
      trim: true,
      maxlength: 500,
    },

    content: {
      type: [String],
      required: true,

      validate: {
        validator(value) {
          return (
            Array.isArray(value) &&
            value.some(
              (paragraph) =>
                typeof paragraph === "string" && paragraph.trim().length > 0,
            )
          );
        },

        message: "Article content cannot be empty.",
      },
    },

    /* =====================================================
       OWNERSHIP
    ===================================================== */

    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    /*
     * Display snapshot only.
     *
     * userId is the real article owner.
     */
    author: {
      type: String,
      required: true,
      trim: true,
      maxlength: 30,
    },

    /* =====================================================
       STATUS
    ===================================================== */

    status: {
      type: String,
      enum: ["active", "archived"],
      default: "active",
      index: true,
    },

    /* =====================================================
       IMAGE
    ===================================================== */

    /*
     * Avoid returning binary data in
     * ordinary Article.find() queries.
     */
    imageBuffer: {
      type: Buffer,
      default: undefined,
      select: false,
    },

    imageMimeType: {
      type: String,
      default: "",
      trim: true,
    },

    imageUrl: {
      type: String,
      default: "",
      trim: true,
    },

    /* =====================================================
       PRESENTATION
    ===================================================== */

    color: {
      type: String,
      default: "bg-zinc-500",
      trim: true,
      maxlength: 80,
    },

    /*
     * Keep for compatibility with
     * your current frontend.
     *
     * createdAt remains the real
     * timestamp.
     */
    date: {
      type: String,

      default: () => new Date().toISOString().split("T")[0],
    },
  },
  {
    timestamps: true,
    versionKey: false,
  },
);

/* =========================================================
   INDEXES
========================================================= */

/*
 * Trainer article feed:
 *
 * userId + active status + newest first
 */
articleSchema.index({
  userId: 1,
  status: 1,
  createdAt: -1,
});

/*
 * Main PokéSocial feed.
 */
articleSchema.index({
  status: 1,
  createdAt: -1,
});

/* =========================================================
   NORMALIZATION
========================================================= */

articleSchema.pre("validate", function () {
  if (this.title) {
    this.title = String(this.title).trim();
  }

  if (this.desc) {
    this.desc = String(this.desc).trim();
  }

  if (this.author) {
    this.author = String(this.author).trim();
  }

  if (this.name) {
    this.name = String(this.name).toLowerCase().trim();
  }

  if (Array.isArray(this.content)) {
    this.content = this.content
      .map((paragraph) => String(paragraph || "").trim())
      .filter(Boolean);
  }
});

module.exports =
  mongoose.models.Article || mongoose.model("Article", articleSchema);
